# Предложения об аренде

## Получить предложения об аренде по идентификатору

GET http://localhost:4000/offers/6546c943af61c0731b1e9156 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1NDZjNWM5NmJhNWE1Y2U1MmIzYTY2YyIsImVtYWlsIjoiam9obkBnb2x0Lm5ldCIsImlhdCI6MTY5OTEzNjk4MiwiZXhwIjoxNjk5MzA5NzgyfQ.B-KpsMSrMt1J47YteF8BfLD_4Ge9088HjiPRSO0HqqU
###

## Получить список предложений об аренде
GET http://localhost:4000/offers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1NDZhNjViNDJiMjgyYmU3NmJmMzMwMSIsImVtYWlsIjoiam9obkBnb2x0Lm5ldCIsImlhdCI6MTY5OTEyODk0OSwiZXhwIjoxNjk5MzAxNzQ5fQ.R0Gj9V-D3E222q67lRKZoUeYFVrWm6fxpv1P9ev6ghE

###

## Удалить предложение об аренде по идентификатору

DELETE http://localhost:4000/offers/6546b35ca093d880bcdce2ba HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1NDZhNjViNDJiMjgyYmU3NmJmMzMwMSIsImVtYWlsIjoiam9obkBnb2x0Lm5ldCIsImlhdCI6MTY5OTEyODk0OSwiZXhwIjoxNjk5MzAxNzQ5fQ.R0Gj9V-D3E222q67lRKZoUeYFVrWm6fxpv1P9ev6ghE

###

## Создать новое предложение об аренде

POST http://localhost:4000/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1NDZjNWM5NmJhNWE1Y2U1MmIzYTY2YyIsImVtYWlsIjoiam9obkBnb2x0Lm5ldCIsImlhdCI6MTY5OTEzNjk4MiwiZXhwIjoxNjk5MzA5NzgyfQ.B-KpsMSrMt1J47YteF8BfLD_4Ge9088HjiPRSO0HqqU

{
  "title": "Дом от Джона Голта",
  "description": "Отличный теплый дом, с камином и баней",
  "city": "Dusseldorf",
  "isPremium": true,
  "previewPhoto": "preview-image-1.jpg",
  "photos": ["general-image-1.jpg", "general-image-2.jpg", "general-image-3.jpg"],
  "type": "house",
  "rooms": 4,
  "guests": 4,
  "cost": 5000,
  "features": ["BREAKFAST"],
  "geo": {"latitude": 51.225402,	"longitude": 6.776314}
}

###

## Обновить предложение об аренде

PATCH http://localhost:4000/offers/6546b35ca093d880bcdce2ba HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1NDZjNWM5NmJhNWE1Y2U1MmIzYTY2YyIsImVtYWlsIjoiam9obkBnb2x0Lm5ldCIsImlhdCI6MTY5OTEzNjk4MiwiZXhwIjoxNjk5MzA5NzgyfQ.B-KpsMSrMt1J47YteF8BfLD_4Ge9088HjiPRSO0HqqU

{
  "title": "Дом на берегу озера рядом с избушкой",
  "cost": 33000
}

###

## Получить список избранных предложений об аренде

GET  http://localhost:4000/offers/favorites/all HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1NDZhNjViNDJiMjgyYmU3NmJmMzMwMSIsImVtYWlsIjoiam9obkBnb2x0Lm5ldCIsImlhdCI6MTY5OTEyODk0OSwiZXhwIjoxNjk5MzAxNzQ5fQ.R0Gj9V-D3E222q67lRKZoUeYFVrWm6fxpv1P9ev6ghE

###

## Добавить (удалить) предложение об аренде в(из) Favorites

PATCH  http://localhost:4000/offers/6546b35ca093d880bcdce2ba/favorites HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1NDZhNjViNDJiMjgyYmU3NmJmMzMwMSIsImVtYWlsIjoiam9obkBnb2x0Lm5ldCIsImlhdCI6MTY5OTEyODk0OSwiZXhwIjoxNjk5MzAxNzQ5fQ.R0Gj9V-D3E222q67lRKZoUeYFVrWm6fxpv1P9ev6ghE

###

## Получить список премиальных предложений об аренде

GET  http://localhost:4000/offers/premium/Hamburg HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1NDZhNjViNDJiMjgyYmU3NmJmMzMwMSIsImVtYWlsIjoiam9obkBnb2x0Lm5ldCIsImlhdCI6MTY5OTEyODk0OSwiZXhwIjoxNjk5MzAxNzQ5fQ.R0Gj9V-D3E222q67lRKZoUeYFVrWm6fxpv1P9ev6ghE

###
